### ISSUE TITLE
Convert matrix into midi file 

### ISSUE THREAD

**Issue by jlian2** [salu133445/musegan#101]
I have seen:

m = Multitrack('./test.npz')
m.write('./test.mid')

But my result is a matrix, once I convert it into npz, it seems that I cannot convert it into midi showing that "json file is missing". (I do not use your code and just want to know how to generate midi file from a matrix)

**Comment by salu133445** [comment]
Hi,

You might find the following snippet helpful.

```python
from pypianoroll import Multitrack, Track

track = Track(pianoroll=some_matrix, program=0, is_drum=False)
multitrack = Multitrack(tracks=[track], tempo=120.0, beat_resolution=24)

multitrack .write("./test.mid")
```

Documentation for the arguments can be found [here](https://salu133445.github.io/pypianoroll/multitrack.html).

Information about the NPZ format for storing multitrack pianorolls can be found [here](https://salu133445.github.io/pypianoroll/save_load.html).

Thanks.
