### ISSUE TITLE
About training ldp-5 npz file

### ISSUE THREAD

**Issue by jlian2** [salu133445/musegan#102]
I just randomly pick a npz from training set:
![image](https://user-images.githubusercontent.com/61141271/84069393-7027c880-a998-11ea-9562-69173522de8b.png)
So what does "indpr", "indices", "shape", "data" mean respectively?

**Comment by jlian2** [comment]
It seems I have figured out what those mean. I am now confused of "program" in 'info.json'

**Comment by salu133445** [comment]
Hi,

The program number is used to indicate the instrument sound to use in MIDI. Please see [here](https://en.wikipedia.org/wiki/General_MIDI#Program_change_events) for what each number corresponds to.

Thanks.
