### ISSUE TITLE
Where is the json file?

### ISSUE THREAD

**Issue by jlian2** [salu133445/musegan#103]

**Comment by jlian2** [comment]
I cannot convert npy to midi directly into midi using multitrack......

**Comment by salu133445** [comment]
Sorry. I could not understand your question. Please provide more details. Thanks.

**Comment by salu133445** [comment]
I guess you are asking how to convert the output arrays into MIDI files. If you want to convert the output files into MIDI files, you could load the generated `.npz` files by Pypianoroll and write them into MIDI files. Here is an example.

```
from pypianoroll import Multitrack

m = Multitrack('./test.npz')
m.write('./test.mid')
```

**Comment by iSuckAtCodingPleaseHelp** [comment]
When saving my Multitrack using 
`multitrack.save(name, compressed=True)`
it does not include a .json files in the .npz 
Thus when I try 
`pypianoroll.load(path)`
I get the error

> RuntimeError: Cannot find `info.json` in the NPZ file.

`RuntimeError                              Traceback (most recent call last)
<ipython-input-32-58686c830663> in <module>()
      3 for path in paths:
      4   print(path)
----> 5   nps.append(pypianoroll.load(path))

/usr/local/lib/python3.7/dist-packages/pypianoroll/inputs.py in load(path)
     42     with np.load(path) as loaded:
     43         if "info.json" not in loaded:
---> 44             raise RuntimeError("Cannot find `info.json` in the NPZ file.")
     45 
     46         # Load the info dictionary

RuntimeError: Cannot find `info.json` in the NPZ file.`


Any suggestions?
