### ISSUE TITLE
fatal error: numpy/arrayobject.h: No such file or directory

### ISSUE THREAD

**Issue by axel578** [salu133445/musegan#105]
This error keep appearing : fatal error: numpy/arrayobject.h: No such file or directory

log: Collecting wheel>=0.26; python_version >= "3" (from tensorboard==1.10.0->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl
Building wheels for collected packages: SharedArray
  Running setup.py bdist_wheel for SharedArray ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jefuq9o9/SharedArray/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpwhrohqqfpip-wheel- --python-tag cp36:
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_ext
  building 'SharedArray' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c ./src/map_owner.c -o build/temp.linux-x86_64-3.6/./src/map_owner.o
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c ./src/map_owner_mlock.c -o build/temp.linux-x86_64-3.6/./src/map_owner_mlock.o
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c ./src/map_owner_msync.c -o build/temp.linux-x86_64-3.6/./src/map_owner_msync.o
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c ./src/map_owner_munlock.c -o build/temp.linux-x86_64-3.6/./src/map_owner_munlock.o
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c ./src/shared_array.c -o build/temp.linux-x86_64-3.6/./src/shared_array.o
  ./src/shared_array.c:24:10: fatal error: numpy/arrayobject.h: No such file or directory
   #include <numpy/arrayobject.h>
            ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by salu133445** [comment]
It looks like a SharedArray installation issue. This might be relevant -> https://github.com/andersbll/cudarray/issues/25#issuecomment-146217359.

**Comment by salu133445** [comment]
Close the issue as there has been no recent updates.

**Comment by salu133445** [comment]
Close the issue as there has been no recent updates.
