### ISSUE TITLE
ValueError: Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by kiomer404** [salu133445/musegan#106]
./scripts/process_data.sh
Loading data from '/mnt/c/Users/kiomer/musegan/scripts/../data/train_x_lpd_5_phr.npz'.
Traceback (most recent call last):
  File "/mnt/c/Users/kiomer/musegan/scripts/../src/process_data.py", line 76, in <module>
    main()
  File "/mnt/c/Users/kiomer/musegan/scripts/../src/process_data.py", line 63, in main
    with np.load(filepath) as loaded:
  File "/home/kiomer/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 444, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

Problem as above

**Comment by salu133445** [comment]
This is weird as there is no pickled data actually. I just tried loading it in Python 3.7.5 with Numpy 1.18.2, and it works. What versions of Python and Numpy are you using?

**Comment by salu133445** [comment]
I am closing the issue as there has been no update for months.

**Comment by MattHuntebrinker** [comment]
I'm getting this same error, installed Python 3.7.5 and Numpy 1.18.2

**Comment by salu133445** [comment]
Thanks for reporting. The download script does not seem to work anymore. I've changed it to use `gdown` to download files from Google Drive instead. (bbbd9f9)
