### ISSUE TITLE
cannot find version tensorflow-gpu==1.10.1

### ISSUE THREAD

**Issue by jamesliu** [salu133445/musegan#109]
Couldn't successfully run 'pip install -r requirements.txt' because 1.10.1 is too old. I change tensorflow version to 1.15.2 in the requirements.txt and successfully install it.

**Comment by jamesliu** [comment]
Is it possible to use tensorflow 2.x? Thanks.

**Comment by salu133445** [comment]
We don't have currently a plan on upgrading the code to TensorFlow 2.

**Comment by danigbp** [comment]
Could you please tell which versions of all packages did you use? Thank you in advance

**Comment by salu133445** [comment]
Please check either the Pipfile or the requirements.txt in the root directory. You might also find the 'prerequisites' section in the README helpful. Thanks.
