### ISSUE TITLE
got an unexpected keyword argument 'beat_resolution'

### ISSUE THREAD

**Issue by boobootoo2** [salu133445/musegan#112]
When I run
./scripts/run_inference.sh "./exp/default/" "0"

I get this error 
Invalid argument: TypeError: __init__() got an unexpected keyword argument 'beat_resolution'

I do not see any new *.npz files

$ find . -name "*.npz" -print
./data/train_x_lpd_5_phr.npz

I am wondering if I setup my environment correctly? Do I have to use Tensorflow with GPU?

**Comment by salu133445** [comment]
Seems like an error related to Pypianoroll. Could you downgrade Pypianoroll to version 0.5.3? Let me know if this works so that I can update the dependencies. Thanks.

**Comment by boobootoo2** [comment]
I was able to configure the environment and get further along I have another issue though I'll open another issue
