### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'train_x_lpd_5_phr'

### ISSUE THREAD

**Issue by Abhiram-921** [salu133445/musegan#116]
![Screenshot from 2021-03-06 01-56-14](https://user-images.githubusercontent.com/56429984/110169783-339dd600-7e1f-11eb-8523-417ca5b41ef8.png)

I am getting this error while I try to train the model using `./scripts/run_train.sh "./exp/my_experiment/" "0"` even though the file `train_x_lpd_5_phr` is present in the directory, I have followed the steps sequentially given in README

**Comment by ayushg0201** [comment]
Abhiram you are such a khaliyar

**Comment by danghoangnhan** [comment]
@Abhiram-921  i'm getting the same error , can you tell me how to solve it
