### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by eurismarpires** [salu133445/musegan#12]
I found the project very interesting. I want to run to learn. I tried to run main.py but I came across the error: FileNotFoundError: [Errno 2] No such file or directory: 'lastfm_alternative_8b_phrase'.

I downloaded this lastfm_alternative_8b_phrase.npy file.
I put it in the training_data folder and also inside the musegan folder. Then I tried to enter the full path of the file.
I also removed the .npy extension but it still did not work. what am I doing wrong?

Thank you!

**Comment by salu133445** [comment]
Did you set the SETUP['training_data_location'] to 'hd'? This will load the data from the hard disk instead of the shared memory (via SharedArray package). The default configuration ('sa') assume that the training data is stored at the shared memory.

btw, we recommend to store your data in shared memory (if possible) to save the data loading time.

**Comment by eurismarpires** [comment]
Do you have any examples of how to save the data to shared memory?

**Comment by salu133445** [comment]
We are using [SharedArray](https://pypi.org/project/SharedArray/) package. You can use the python script `training_data/store_to_sa.py` to store your data to shared memory. (Run `python store_to_sa.py -h` to see what command line arguments are available.)

**Comment by eurismarpires** [comment]
The following error appears when I run the file:
python store_to_sa.py lastfm_alternative_5b_phrase.npy --name lastfm_alternative_5b_phrase --prefix sa
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 428, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '<'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "store_to_sa.py", line 37, in <module>
    main()
  File "store_to_sa.py", line 24, in main
    data = np.load(filepath)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 431, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'lastfm_alternative_5b_phrase.npy' as a pickle

**Comment by salu133445** [comment]
Did you download the training data through the scripts? If so, please download it through [this link](https://drive.google.com/uc?export=download&id=1F7J5n9uOPqViBYpoPT5GvE4PjCWhOyWc). Seems like the scripts are not working.

**Comment by eurismarpires** [comment]
It worked fine with this file. thank you very much!
