### ISSUE TITLE
Track-conditional generation error

### ISSUE THREAD

**Issue by Yan8150** [salu133445/musegan#122]
Hello, when I use the pretrained models to generate music using track-conditional Generation, I meet some error.
I had modify ./exp/accompaniment/piano/config.yaml and params.yaml.
![config](https://user-images.githubusercontent.com/31834843/124757961-b3b88180-df60-11eb-9de9-b50be0d0eb0d.jpg)

![params](https://user-images.githubusercontent.com/31834843/124758177-e6627a00-df60-11eb-9d48-5d3353aed19c.jpg)

![error](https://user-images.githubusercontent.com/31834843/124758363-13169180-df61-11eb-81e3-1eb0cd829ef3.jpg)

**Comment by ikarus-999** [comment]
This Error STILL remains...

How to track-conditional generation????
