### ISSUE TITLE
How to prepare new training data?

### ISSUE THREAD

**Issue by RoyLiuYihong** [salu133445/musegan#13]
Greetings! 
It's really interesting to see and practice the whole MuseGAN model!!! However, when I want to modify the model with fewer tracks, it comes that new training data is needed. But I only find 
 a data download link [lastfm_alternative_5b_phrase.npy ](https://drive.google.com/uc?export=download&id=1F7J5n9uOPqViBYpoPT5GvE4PjCWhOyWc) and an old version data preprocess in [v1 model](https://github.com/salu133445/musegan/tree/master/v1/training). I'm just wondering can you describe more details about how to create a new training data like [lastfm_alternative_5b_phrase.npy ](https://drive.google.com/uc?export=download&id=1F7J5n9uOPqViBYpoPT5GvE4PjCWhOyWc)?

**Comment by salu133445** [comment]
Hi, the new training data is collected by randomly picking six four-bar phrases from each song with an *alternative* tag in the LPD-cleansed datasets (see [here](https://salu133445.github.io/lakh-pianoroll-dataset/dataset.html)). This is how `lastfm_alternative_5b_phrase.npy` and `lastfm_alternative_8b_phrase.npy` are created. For the original training data (i.e. `tra_phr.npy` in v1), please follow the old data preprocessing codes.

**Comment by SPGB** [comment]
I have the same issue. I found the LPD-cleansed datasets and now have a collection of .npz files, but I don't see how to combine them into a single numpy array.

**Comment by salu133445** [comment]
The code for collecting piano-roll bars/phrases from npz files to a single large npy file is a bit messy, so we didn't upload it. I would suggest you to write for your own. You can simply pick (randomly or according to some strategies) some bars/phrases from each npz file and stack them into one npy file. The npz files in LPD can be loaded by the pypianoroll package as follows.

```python
from pypianoroll import Multitrack
m = Multitrack('path/to/your/npz/file.npz')
```

The piano-roll matrix can then be accessed by `m.pianoroll`.
