### ISSUE TITLE
Unable to retrieve pianoroll dataset when running in colab.

### ISSUE THREAD

**Issue by lllizzadro** [salu133445/musegan#133]
Doing a project for my Neural Nets class and looking for music generation-related GANs to draw inspiration from. Tried to run your notebook in colab and am getting the following error...
![image](https://user-images.githubusercontent.com/90274668/161613806-f285f100-2707-4ce3-88ee-78a0a17f5a7a.png)

Is the data still on that google drive?

Great Work on this Network, I appreciate you putting this out there.

**Comment by salu133445** [comment]
Hi, it seems like a bug of gdown (wkentaro/gdown#43). Please upgrade gdown to the latest version (`pip install --upgrade gdown`). Let me know if that works. Thanks!

**Comment by lllizzadro** [comment]
Yes that was the problem. Thanks for the timely response and making your work available.
