### ISSUE TITLE
Error: no module named SharedArray

### ISSUE THREAD

**Issue by iris03** [salu133445/musegan#14]
The full error is below:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    '.'.join(('musegan', CONFIG['exp']['model'], 'models')))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\PU40005904\Downloads\musegan-master\musegan-master\musegan\musegan\models.py", line 9, in <module>
    from musegan.utils.metrics import Metrics
  File "C:\Users\PU40005904\Downloads\musegan-master\musegan-master\musegan\utils\metrics.py", line 7, in <module>
    import SharedArray as sa
ModuleNotFoundError: No module named 'SharedArray'

SharedArray is not being installed when pip install sharedarray is ran, error is:

  Failed building wheel for sharedarray
  Running setup.py clean for sharedarray
Failed to build sharedarray
Installing collected packages: sharedarray
  Running setup.py install for sharedarray ... error
    Complete output from command "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\PU40005904\\AppData\\Local\\Temp\\pip-install-6nedy54o\\sharedarray\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PU40005904\AppData\Local\Temp\pip-record-n229w795\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'SharedArray' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-Ic:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\numpy\core\include" "-Ic:\program files (x86)\microsoft visual studio\shared\anaconda3_64\include" "-Ic:\program files (x86)\microsoft visual studio\shared\anaconda3_64\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tc.\src\map_owner.c /Fobuild\temp.win-amd64-3.6\Release\.\src\map_owner.obj
    map_owner.c
    .\src\map_owner.c(19): fatal error C1083: Cannot open include file: 'sys/mman.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command ""c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\PU40005904\\AppData\\Local\\Temp\\pip-install-6nedy54o\\sharedarray\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PU40005904\AppData\Local\Temp\pip-record-n229w795\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\PU40005904\AppData\Local\Temp\pip-install-6nedy54o\sharedarray\

If someone has a way to make this work, please help.
thanks.

**Comment by iris03** [comment]
I found that sharedArray is only compatible with Linux/Mac.
Can anyone suggest a way to run that on Windows?
or any good alternative to this module?
Thanks.

**Comment by salu133445** [comment]
I don't know any alternative package for SharedArray on Windows. But you may try loading the training data from the hard disk. This can be a relatively small overhead since you only need to load the data once before the training.
1. put the training data under `training_data` directory
2. set `SETUP['training_data_location']` to 'hd'.

**Comment by iris03** [comment]
It worked, though training took a lot of time.
Thanks for uploading this masterpiece of work and sharing it with us.
It was a pleasure understanding such a well-defined model.
Thanks a lot!

**Comment by iris03** [comment]
I there a way to run the metrics.py file without SharedArray use?
Thanks.

**Comment by iris03** [comment]
Thanks once again!

**Comment by phanirithvij** [comment]
@salu133445 I don't really understand what you mean.

**Comment by phanirithvij** [comment]
1. Where do I set it?
2. Do I have to refactor the whole code by removing all SharedArray instances in all the files?

**Comment by salu133445** [comment]
1. There are two ways to do so. If you want to change the default behaviors, you can modify the file `src/musegan/default_config.yaml` by changing the value of `data_source` to `npy` or `npz` (depends on how you store the pianorolls on the hard disk). Or, you can modify the created configuration file (`config.yaml` in the given experiment folder) after setting up an experiment by running the script `setup_exp.sh`. The second approach will not change the default configurations, so you need to modify the settings manually for each experiment.

2. SharedArray is only used in `src/musegan/data.py` and it will only be imported dynamically when `data_source` in the configuration file is set to `sa`. Hence, you don't need to refactor the source code.

Thanks.

**Comment by soheilKLQC** [comment]
Did someone found a solution? I'm using Linux and it still does not work.
