### ISSUE TITLE
Evaluation model

### ISSUE THREAD

**Issue by iris03** [salu133445/musegan#15]
Hi,
I have trained the model and now I just want to run the evaluation again and again to generate new music.
I have seen that even when I enter the pretrained directory, it is training the model again and then producing the results.
Is there a way by which only the evaluation can be run and a new music is produced based on the model it has learned in the pretrained directory. i.e only the midi file comes as output and training is not proceeded.

Thanks.

**Comment by salu133445** [comment]
You may need to modify `main.py` for this, e.g., in your case, you may want to replace `gan.train(x_train, CONFIG['train'])` with something else.

Some possibly related methods of `musegan.Model`:

- `musegan.Model.run_sampler()`
- `musegan.Model.save_samples()` (Note that you can provide argument `postfix` to avoid overwriting.)

**Comment by iris03** [comment]
Thanks! That helped a lot!
