### ISSUE TITLE
How to make track conditional model work?

### ISSUE THREAD

**Issue by iris03** [salu133445/musegan#18]
Hi!
I wanted to know the steps to make track conditional model work, as in if I provide one instrument's melody of my own, how will the model generate new music around it?
Or is there a way it could generate new music around a multi-track melody?
Thanks.

**Comment by salu133445** [comment]
For the track-conditional model, please use MuseGANv1.

**Comment by salu133445** [comment]
The latest version (MuseGANv3) now supports the track-conditional model (namely, the accompaniment model) as well.
