### ISSUE TITLE
the issues of dataset for cleaning data 

### ISSUE THREAD

**Issue by zzdang** [salu133445/musegan#2]
In the setting.yaml in preprocessing ,I saw lmd_dir and lpd_dir. I'm confusing about it ,how should I do to prepare the midi data to do data clean?
Thank you very much

**Comment by RichardYang40148** [comment]
maybe this blogpost helps?
https://salu133445.github.io/musegan/dataset

**Comment by salu133445** [comment]
We've uploaded a new version of preprocessing code using Pypianoroll package.
