### ISSUE TITLE
Can not download the training data set.

### ISSUE THREAD

**Issue by VickyChing** [salu133445/musegan#26]
The paper is very good and I want to learn it.. However I tried to download the training data through the scripts, and it failed because the network is unreachable. And then I tried to download it through the links [https://drive.google.com/uc?export=download&id=1F7J5n9uOPqViBYpoPT5GvE4PjCWhOyWc](https://drive.google.com/uc?export=download&id=1F7J5n9uOPqViBYpoPT5GvE4PjCWhOyWc) or [https://drive.google.com/uc?export=download&id=1x3CeSqE6ElWa6V7ueNl8FKPFmMoyu4ED](https://drive.google.com/uc?export=download&id=1x3CeSqE6ElWa6V7ueNl8FKPFmMoyu4ED), but it still doesn't work because of the network, and I have used several VPN, still so. Can you send to the Baidu Netdisk or some tools else available so that I can download it? Thank you a lot!

**Comment by salu133445** [comment]
I think the links are working now.
