### ISSUE TITLE
I have some question about you paper.

### ISSUE THREAD

**Issue by guanfaqian** [salu133445/musegan#27]
In you paper "MuseGAN: Multi-track Sequential Generative Adversarial Networks for Symbolic Music Generation and Accompaniment",the figure5 is only the hybrid model of Figure 3. The other two models are not drawn.
Is it correct for me to understand this?

**Comment by guanfaqian** [comment]
Thank you very much for taking the time to answer questions.

What is the version of the code you uploaded?There are base, musegan versions, and v1 inside them. What is the difference?

**Comment by salu133445** [comment]
Please refer to #28.
