### ISSUE TITLE
There are base, musegan versions, and v1 inside them. What is the difference?

### ISSUE THREAD

**Issue by guanfaqian** [salu133445/musegan#28]

**Comment by salu133445** [comment]
- Version 1: (archived to `v1` folder) This version was used to conduct all the experiments in the AAAI paper (MuseGAN). The code is a bit messy. This version only has a script for training (`v1/main.py`). No pretrained model is available.
- Version 2: (archived to `v2/` folder) This version was used to conduct all the experiments for the ISMIR paper (BinaryMuseGAN). The code is more well organized. This version has only a script for training as well (`v2/main.py`). There are some issues on the pretrained models.
- Version 3: This latest version provides scripts for training, inference and Interpolation. The environment related files are also provides for reproducibility. We also provide some pretrained models.

**Comment by salu133445** [comment]
The following chart might help.

| version | paper | scripts | pretrained models |
|:---:|:---:|:---:|:---:|
| v1 | AAAI | training only | X |
| v2 | ISMIR | training only | O |
| v3 | - | training, inference, Interpolation | O |
