### ISSUE TITLE
the preprocessing of train dataset

### ISSUE THREAD

**Issue by zzdang** [salu133445/musegan#3]
Hi ,I don't know how to get 'tra_X_phrase_all' in main.py, I run the preprocess code and I only get many npz files. What I should do to get the 'tra_X_phrase_all' file?
Thank you very much!

**Comment by wayne391** [comment]
Hello, you can prepare this file by yourself.  'tra_X_phrase_all' is an ".npy" file and its shape is 
(# of samples, # of time steps, range of pitch, # of track).

For example, in one of our case is (50266, 384, 84, 5). It means:
(a) we have 50266 phrases for training
(b) 96 (time resolution) x 4 (# of bar), so we have 384 time steps
(c) we use 7 octave so the range of pitches is 84 (12 x 7)
(d) there are five tracks

We encourage you to prepare your own dataset. You can select desired genres and combine tracks arbitrarily after finishing the pre-processing part.

**Comment by zzdang** [comment]
ok,thank you,but I don'T similar with the module of python to read and write piano roll files,can you open some code to deal with    them?

**Comment by wayne391** [comment]
Hello, we've opened the training data. You can find it in the readme.
The file "tra_X_phrase_all" is the same with "tra_phr.npy". You can have a try.

For the manipulation package or toolbox on piano rolls, I recommend you to use 'pypianoroll':
https://github.com/salu133445/pypianoroll

It can facilitate the processing step and help you to build your own piano-roll dataset. 
Have fun~

**Comment by lilacheson** [comment]
Hello guys! I'm also confused about how to get the training data in .npy format from a bunch of .npz files. Do you have any suggestions? I have read tutorials of pypianoroll but still at lost. Thanks a lot!

**Comment by wayne391** [comment]
Hello, I've update our page. Because we did a lot work on pre-processing
the training data, it's hard to explain without any codes. Therefore, we
decide to let them opened:
https://github.com/salu133445/musegan/tree/master/training

These codes are not well-organized because they are only for internal use
originally. However, we believe it can make it easier for you to follow our
work.

**Comment by lilacheson** [comment]
Thanks a lot for your sharing processing methods and codes!
