### ISSUE TITLE
Why do my evaluation indicators show a "nan" value?

### ISSUE THREAD

**Issue by guanfaqian** [salu133445/musegan#30]
I ran your musegan code for a total of 10 rounds. The effect is not particularly good. Is this normal?

At the same time, I loaded the indicator matrix and wanted to see the indicator score, but the "nan" value appeared.

At the same time, I still have some questions sent to your google mailbox.

The loaded indicator content is as follows (Is this normal?):

{'score_matrix_mean': array([[  0.6484375 ,   0.6796875 ,   0.        ,   0.        ,
          0.3125    ,   0.7578125 ,   0.8203125 ,   0.8515625 ],
       [  5.33333333,  13.56097561,   9.3046875 ,   4.53125   ,
         12.71590909,  12.12903226,  10.34782609,  10.63157895],
       [         nan,   0.56565087,   0.42536851,   0.48969937,
          0.4198412 ,   0.39742527,   0.13204621,   0.33636354],
       [         nan,   0.66996951,   0.52701823,   0.13850911,
          0.52864583,   0.30510753,   0.19157609,   0.30921053],
       [         nan,   0.73237388,   0.7759802 ,   0.71933473,
          0.75686481,   0.84366099,   0.90060636,   0.94346961],
       [  0.52668201,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan],
       [         nan,   4.2195122 ,   4.125     ,   2.40625   ,
          5.31818182,   3.03225806,   4.86956522,   3.        ]]), 'score_pair_matrix_mean': array([ 1.18790474])}

**Comment by guanfaqian** [comment]
Someone ran through the code and saw eval?

**Comment by salu133445** [comment]
A nan means the corresponding metric is not defined for that corresponding track. So the nans in the final score matrix comes from the fact that

- drum pattern (DP; the 6th metric) is only defined for the drum track
- all other matrices are not defined for the drum track

Note that `CONFIG['model']['metric_map']` in `config.py` determines whether we should compute a certain metric for a specific track.
