### ISSUE TITLE
Issue of Pretrained Model 

### ISSUE THREAD

**Issue by dianyo** [salu133445/musegan#32]
Hi, 
   I want to use pretrained model to reproduce the result, but when I load the pretrained model,
this error happened: `NotFoundError: Key GAN/G/bar_main_0/Layer_1/batch_norm/beta not found in checkpoint`. Is the pretrained model compatible with the latest version of code? If not, is the compatible version exist in this repository?

**Comment by salu133445** [comment]
We have updated the code to v3. It should now be easier to load the pretrained models. Please refer to the README file to see how to use the pretrained models.
