### ISSUE TITLE
Why I train so long with a GTX 1080 GPU?

### ISSUE THREAD

**Issue by VickyChing** [salu133445/musegan#33]
Hi, I have trained the musegan hybrid model with a GTX 1080 GPU for a month, but have not finished yet, it iterated 6 epoch so far, which is very different from what you described in the article. Is it something wrong with my operation? In addition, the G_loss is negative?
like these:
   6  |   68/ 429 | 833.89 |      64.655495 |     -16.210884
   6  |   69/ 429 | 837.64 |      49.892788 |      -1.440047
   6  |   70/ 429 | 852.82 |      56.134148 |     -18.617529
   6  |   71/ 429 | 847.19 |      53.495033 |     -15.782113
   6  |   72/ 429 | 845.77 |      48.307137 |       4.247076

**Comment by VickyChing** [comment]
The second question, how can I test the model? should I write a new code to test and where is the testing data? Thank you!

**Comment by salu133445** [comment]
Well.....there's certainly something wrong. The third value is the time spent for a batch. It shouldn't take that long. It only takes 5 sec for a batch on a K80 GPU in my environment. A GTX 1080 should be even faster. It seems that your are training the model on CPU. You can run `nvidia-smi` and
- check if you are using the GPU -> the python process/command should be listed in the bottom block
- check the Volatile GPU Utils -> if <80% at most time, there might be some bottlenecks in the preprocessing and data I/O

**Comment by VickyChing** [comment]
> Well.....there's certainly something wrong. The third value is the time spent for a batch. It shouldn't take that long. It only takes 5 sec for a batch on a K80 GPU in my environment. A GTX 1080 should be even faster. It seems that your are training the model on CPU. You can run `nvidia-smi` and
> 
> * check if you are using the GPU -> the python process/command should be listed in the bottom block
> * check the Volatile GPU Utils -> if <80% at most time, there might be some bottlenecks in the prep

>

**Comment by VickyChing** [comment]
/home/cheng/Downloads/webwxgetmsgimg.jpeg
/home/cheng/Downloads/webwxgetmsgimg (1).jpeg
I have checked the gpu utils, which is always < 60%, but the terminal shows that python3 has 7015 MiB GPU memory usage. Please tell me how to solve it, thank you very much!

**Comment by guanfaqian** [comment]
It's should your error.
I also use 1080.It's my train in two_stage:
   4  |  197/ 859 |   6.09 |      52.351204 |     145.995178
   4  |  198/ 859 |   6.09 |      56.314610 |     118.013321
   4  |  199/ 859 |   6.08 |      53.869148 |     124.766968
   4  |  200/ 859 |   6.09 |      58.309795 |     200.821503
   4  |  201/ 859 |   6.09 |      59.010063 |     106.380798
   4  |  202/ 859 |   6.09 |      68.212479 |     157.099152
   4  |  203/ 859 |   6.09 |      65.960938 |     169.851349
