### ISSUE TITLE
Lpd-17-cleansed only rock music?

### ISSUE THREAD

**Issue by guanfaqian** [salu133445/musegan#36]
Does lpd-17-cleansed have other genre of music?

And how is your 17 going to track 8

**Comment by salu133445** [comment]
LPD-cleansed contain all the genres (different from what appeared on the paper). From 17 tracks to 8 tracks, we chose the top eight common instrument families for alternative genre, the training data we used by default here. Note that we used _Alternative_ genre in BinarMuseGAN and _Rock_ genre in MuseGAN.

**Comment by guanfaqian** [comment]
I only saw it from LMD to cleaned on your lakh-pianoroll-dataset. But cleansed only handles the npz format, not the npy format you gave.
I didn't see how you picked the rock, and how the npz file got to your final shape=(-1,4,94, 84, 5) This npy file.
I tried to go from npz to npy format myself, but I didn't know how to deal with it at this step."return Multitrack(None, tracks, multitrack.tempo, multitrack.downbeat,
                      multitrack.beat_resolution, multitrack.name)"
Can you give me these two parts of the code?

**Comment by guanfaqian** [comment]
I took a closer look at the library you wrote. Solved the problem of getting multiple tracks. But still don't know how to get music from Cleaned to Rock.

**Comment by salu133445** [comment]
Please refer to the other repository (https://github.com/salu133445/lakh-pianoroll-dataset). Thanks.
