### ISSUE TITLE
what is u use rock tag?

### ISSUE THREAD

**Issue by guanfaqian** [salu133445/musegan#38]
http://www.ifs.tuwien.ac.at/mir/msd/
I take the genre tag of LMP.But I don't konw you that Which kinds of music do you classify as rock?

In my oponion,rock include "Grunge Emo Metal"     "Alternative"     "Metal Death"   "Metal Heavy" "Punk" "Reggae"  "Rock Alternative" "Rock College" "Rock Contemporary"  "Rock Hard"   "Rock Neo Psychedelia"

All types are as follows:
Genre Name | Number of Tracks
-- | --
Big Band | 3,115
Blues Contemporary | 6,874
Country Traditional | 11,164
Dance | 15,114
Electronica | 10,987
Experimental | 12,139
Folk International | 9,849
Gospel | 6,974
Grunge Emo | 6,256
Hip Hop Rap | 16,100
Jazz Classic | 10,024
Metal Alternative | 14,009
Metal Death | 9,851
Metal Heavy | 10,784
Pop Contemporary | 13,624
Pop Indie | 18,138
Pop Latin | 7,699
Punk | 9,610
Reggae | 5,232
RnB Soul | 6,238
Rock Alternative | 12,717
Rock College | 16,575
Rock Contemporary | 16,530
Rock Hard | 13,276
Rock Neo Psychedelia | 11,057

**Comment by guanfaqian** [comment]
Does your "with a Rack tag" mean 5 tags that are "Rock Alternative""Rock College" "Rock Contemporary"  "Rock Hard"   "Rock Neo Psychedelia"?

**Comment by salu133445** [comment]
We used the [Last.fm](https://labrosa.ee.columbia.edu/millionsong/lastfm) dataset and picked only those who have a _Rock_ tag.
