### ISSUE TITLE
Does anyone have a copy of the original training data?

### ISSUE THREAD

**Issue by salu133445** [salu133445/musegan#39]
We accidentally deleted the original training data (`tra_phr.npy` and `tra_bar.npy`). If you have a copy, please let us know so that we can put them back on the website. Thanks!

**Comment by aaronrmm** [comment]
You could remake them, right? Let me know if it's not possible, because that's what I'm trying to do. Will let you know if I succeed.

**Comment by aaaooooaaa** [comment]
Could this be the reason I'm getting a no "Model checkpoint directory not found" error?

**Comment by salu133445** [comment]
Probably not. Did you download the pretrained models?

If not, please run the following script.
```
./scripts/download_pretrained_models.sh
```
Or, download it manually [here](https://docs.google.com/uc?export=download&id=1gySWtj5_19jGrwIYd_YT11bide8DJHyN).

**Comment by aaronrmm** [comment]
I mean musenet

**Comment by aaronrmm** [comment]
Dude, OpenAI they took your name with musegan.
