### ISSUE TITLE
How and where do you input the track for track conditional generation using v1?

### ISSUE THREAD

**Issue by MehakManiktala** [salu133445/musegan#40]

**Comment by salu133445** [comment]
You can specify the input track by `acc_idx` in `v1/config.py`. The track conditional models are `NowBarHybridConfig`, `NowBarJammingConfig` and `NowBarComposerConfig`.

**Comment by MehakManiktala** [comment]
Thank you!
After training the track conditional generator model, will we be able to use the model to generate music based on a new track fed as input_data to gen_test(input_data, is_eval=True)?

**Comment by salu133445** [comment]
Please refer to `v1/README.md`. Something like the following might work, where `test.npy` is the test data. The number of tracks needs to be five, so you might need to set other tracks to zeros.
```python
with tf.Session() as sess:
    # Load a trained model
    musegan.load(musegan.dir_ckpt)

    # Load test data
    path_test = 'test.npy'
    input_data.add_data(path_test, key='test')

    # Generate samples
    musegan.gen_test(input_data, is_eval=True)
```

**Comment by MehakManiktala** [comment]
thank you!
