### ISSUE TITLE
Why do you use G and D for Normalization and activation layers differently?

### ISSUE THREAD

**Issue by guanfaqian** [salu133445/musegan#41]
Why do you use G and D for Normalization and activation layers differently, G uses bn and relu, D does not use normalization, and uses lrelu to activate.

Is gradient explosion and disappearance adjusted?

**Comment by salu133445** [comment]
We follow the DCGAN paper to use ReLU in the generator and LeakyReLU in discriminator. Applying batch normalization only to generator is suggested by the WGAN-GP paper.
