### ISSUE TITLE
How to listen the result?

### ISSUE THREAD

**Issue by zyoohv** [salu133445/musegan#49]
The result of model are .npy and image files. 

I can not find any audio files such as .mp3 and .mid.

So how to listen the result audio files?

**Comment by salu133445** [comment]
The generated pianorolls are stored in `.npz` format to save space and processing time. You can use the following code to write them into MIDI files.

```python
from pypianoroll import Multitrack

m = Multitrack('./test.npz')
m.write('./test.mid')
```

**Comment by zyoohv** [comment]
Thank you very much!!!

**Comment by Liujingxiu23** [comment]
@ salu133445 Followed your instruction, I can generated npz file using run_inference.sh,  the generated *.npz file(file locoted like accompaniment/bass/results/inference/pianorolls/fake_x_bernoulli_sampling/*.npz) can then be converted to midi using pypianoroll, and then converted to wav which can played using a common audio player.

But how can I combine the five track to finally generate wav like a musical performance， or like the example in https://salu133445.github.io/musegan/
