### ISSUE TITLE
Dataset confusions

### ISSUE THREAD

**Issue by peiherng97** [salu133445/musegan#52]
What is the difference between x_lpd-5_phr_v2.npy, train_x_lpd_5_phr.npz lastfm_alternative_5b_phrase.npy and lastfm_alternative_5b_phrase.npy ? I could not find the first one(x_lpd-5_phr_v2.npy) anymore anywhere.

**Comment by salu133445** [comment]
There should be a file named `x_lpd_5_phr.npy` when we released MuseGANv3. Do you mean this one? 

We later turn the dense array (`x_lpd_5_phr.npy`) into a sparsely encoded array (`x_lpd_5_phr.npz`) to save space. So, these two files are the same data in different encodings and formats.

`lastfm_alternative_5b_phrase.npy` is used in the BinaryMuseGAN paper, where we didn't use any strategies to select the phrases while randomly four-bar phrases from the whole song.

**Comment by peiherng97** [comment]
I found where i downloaded x_lpd-5_phr.npy. Thanks for the clarification !!
