### ISSUE TITLE
Didn't understand significance of 6 in the shape of dataset

### ISSUE THREAD

**Issue by techcentaur** [salu133445/musegan#58]
The dataset shape is 2291*6*4*96*84*8 (with 8 instruments), I don't understand the significance of '6' in this. Can you please help, to tell me what does it mean? I didn't find it in either the docs or the paper.

**Comment by salu133445** [comment]
For `lastfm_alternative_8b_phrase.npy`, we randomly picked six phrases from each song. That's how the 6 comes from. See [here](https://salu133445.github.io/bmusegan/data) for more information of the data.

**Comment by techcentaur** [comment]
Okay. Thanks for the help! :)
