### ISSUE TITLE
Confidence score

### ISSUE THREAD

**Issue by aquastar** [salu133445/musegan#6]
Can somebody tell me which field in meta info is treated as ‘confidence score’ in this work (footnote 7 in the paper), I can see some fields like bars_confidence/beats_confidence/sections_confidence in meta info from LMD, but not sure which one you are using.

**Comment by salu133445** [comment]
The match scores are not included in the MSD meta data. You can find a Match Scores json file at the LMD demo page. (http://colinraffel.com/projects/lmd/)

**Comment by aquastar** [comment]
Thanks! Can you tell me your threshold for matched score in practice, 0.7 or 0.8 ?

**Comment by salu133445** [comment]
We didn't apply a hard threshold. Instead, we pick for each song only one piano-roll having the highest matching scores. Please see the file 'preprocessing/cleanser.py' for details.

**Comment by aquastar** [comment]
Thanks!
