### ISSUE TITLE
Question about the model

### ISSUE THREAD

**Issue by ryf1123** [salu133445/musegan#64]
Thank you so much for you great work and open mind!:clap:
But I feel confused and have two questions when I take a closer look at the code.
1. In the MuseGan version 2, three models - composer, hybrid and jamming are proposed. But there is only one model in the newest code(root/src), and I guess it is a version of the `Composer Model` (am I right?). However, in this version, I cannot find the `tempo generator` but only the `bar generator`. Could you please tell where what's wrong?

2.  I am most confused about that in the `generator` and `discriminator` in your newest version (I mean the version in root/src), I can see code like below,
```
            # Pitch-time private network
            with tf.variable_scope('pitch_time_private'):
                s1 = [conv_layer(h, 16, (1, 1, 12), (1, 1, 12))      # 4, 48, 7
                      for _ in range(self.n_tracks)]
                s1 = [conv_layer(s1[i], 32, (1, 3, 1), (1, 3, 1))    # 4, 16, 7
                      for i in range(self.n_tracks)]
```
According to my knowledge, a `generator` like this will result in a `generator` which can generate 5 similar tracks, because the criticism from the `discriminator` is just one number, instead of 5 to each `generator`. But why the result sounds good when I tried it myself? As for the `discriminator`, the code below is the last few lines of `discriminator` and I think h is supposed to be something like (?, 1).
```
            # Merge all streams
            with tf.variable_scope('merged'):
                h = conv_layer(h, 512, (2, 1, 1), (1, 1, 1))         # 3, 1, 1

            h = tf.reshape(h, (-1, h.get_shape()[-1]))
            h = dense(h, 1)

        return h
```
Thank you again for you help and work.

--- 
yufan

**Comment by salu133445** [comment]
1. Yes. We only implement the composer model in the current version. The model is based on the BinarMuseGAN paper. Please refer to the paper for the design.

2. They are actually five different generators, having different names. And they will later merged into one. Please see the BinaryMuseGAN for the design. Note that it is a list comprehension.
