### ISSUE TITLE
How can I get a music finally?

### ISSUE THREAD

**Issue by Praying** [salu133445/musegan#69]
such as  a xxx.mp3 file?

**Comment by salu133445** [comment]
Please refer to #49 to see how to convert `.npz` files to `.mid` files. You can then synthesize the audio by whatever synthesizer you like.

**Comment by Praying** [comment]
thanks.And I have solve the problem, but the music seem not very nice, do you know the music engine named aiva https://www.aiva.ai/engine, can we generate music like that?

**Comment by salu133445** [comment]
Not likely for now. It is still really difficult for the current algorithms, even the state of the art, to generate very pleasant music in such high-dimensional space (pianorolls or MIDIs). If you would like to build something more practical, you might want to consider other output targets such as lead sheets.
