### ISSUE TITLE
Condition output based on a single midi file in the test phase

### ISSUE THREAD

**Issue by Razzaghnoori** [salu133445/musegan#70]
I am now capable of converting a directory of midi files to a `.npz` file and as I understood, by setting `data_filename` value in the `config.yml` file, I can train a model based on the provided midis.

However, I'm not sure if that serves as a condition to the pre-trained model or trains the model from scratch.

Eventually, I want to feed a midi file to the algorithm and receive another midi file similar to that for instance in the genre but generally different.

**Comment by salu133445** [comment]
Currently we do not support conditional GANs. We only implement the unconditional GANs. However, we do have provide the optimal arguments for the conditions in the generator and the discriminator objects. If you want to implement the conditional GANs, you might need to modify the code for the training session by providing the genre tags as the conditions, and then retrain the model.

If I understand your idea correctly, it should involve both recognition and generation problems. That is, you need an additional recognition model to predict the genre of the input files and then use the conditional GANs to generate some new samples with the predicted genre.

**Comment by Razzaghnoori** [comment]
Thanks. I'm working on it.
