### ISSUE TITLE
How can I use a song to generate a similar music

### ISSUE THREAD

**Issue by lishan5600** [salu133445/musegan#74]
I use anaconda and python3.5. I hope that I can use a song to generate a similar music. I try to solve it, but I can’t. Can you give me some suggestions? I have installed the requested package, except SharedArray. In addition, the test music is midi format.

**Comment by Razzaghnoori** [comment]
Currently, generating track similar to provided track is not quite supported. The infrastructure is somehow there though. First, you need to define a proper condition to be concatenated to the generator's input. You can, for example, train another network to extract music genre and use it as the condition.

[MuseGAN](https://github.com/salu133445/musegan) accepts input in the `.npz` format and produces output in the same format which is basically compressed `.npy`. 

Please refer to #51 for midi to npz and #49 for npz to midi conversion.

**Comment by salu133445** [comment]
Thank you, @Razzaghnoori. Please also refer to #70 for a similar issue.

**Comment by lishan5600** [comment]
Thank you！
