### ISSUE TITLE
About pretrained model and tensorflow

### ISSUE THREAD

**Issue by yang19941128** [salu133445/musegan#75]
Hi,what could I do about the following problem?
INFO:tensorflow:Restoring parameters from /home/boyun/musegan/exp/default/model/model.ckpt-300450
tensorflow           INFO     Restoring parameters from /home/boyun/musegan/exp/default/model/model.ckpt-300450
(boyun) (base) boyun@boyun:~/musegan$ 
You can see above,it can't contitnue. It don't show any error.　I sure the version of the tensorflow is correct. So what suggestion can you provide for me?Thank you for your help!

**Comment by salu133445** [comment]
I am not sure what happened according only to the provided information. You might need to check the log files, which can be found in the 'logs' folder in the experiment directory, and see what cause it to stop. Thanks.

**Comment by yang19941128** [comment]
Thank you for your help and your brilliant work. I got it and it can work.
