### ISSUE TITLE
code for creating a new dataset

### ISSUE THREAD

**Issue by VladJamir** [salu133445/musegan#76]
I was able to derive `lpd` to mydesired dataset which is a collection of `lpd-cleansed` with `lastfm jazz tag` Is there a code for transforming the collection to a one single matrix file like the `train_x_lpd_5_phr.npz`

**Comment by jayelm** [comment]
+1, is it possible to share the code used to extract 4 bar phrases from the midi files? I want to create a version of LPD-17 that keeps all 17 instruments (but has the same shape of `train_x_lpd_5_phr.npz`)

**Comment by salu133445** [comment]
The original code for creating the training data we used in the first version can be found at `musegan/v1/training/`. Note that we use MATLAB to implement the segmentation algorithms.
