### ISSUE TITLE
About the phrase

### ISSUE THREAD

**Issue by yang19941128** [salu133445/musegan#77]
Hi! Could you tell me how to extent the time of the generated phrase ? I tried to get the results, but   each phrase was only a dozen seconds! Thank you for your help!

**Comment by salu133445** [comment]
Unfortunately, we only support fixed-length phrase in the current model. Each phrase is four measures long. If you would like to generate longer phrases, you might need a temporal model that can handle data with variable lengths.

**Comment by yang19941128** [comment]
Sorry, I did not accurately express my meaning in the above. I just wanted a longer continuously music between silence. So, I modified a little bit of the code. I added silence every two phrases. Thanks for your reply!

**Comment by salu133445** [comment]
I see. Good to know you figure it out.
