### ISSUE TITLE
What do you mean by "time-dependent random vectors" in the paper?

### ISSUE THREAD

**Issue by maxichu** [salu133445/musegan#8]
Hi, Wendong,

I'm quite interested in your work of automatic music generation.
And our lab in NUS is also conducting research on music computing.

Basically, I understand the framework, I'm just a little bit confused about
the term "time-dependent random vectors"...

It sounds to me like a random vector you generated with time as a parameter,
but can I ask for some details or basic ideas about how to generate time-dependent random numbers? 
Or you can simply point out from which source file can I find the code of this process. 

Because the long-term structure is really important in music generation, I think time-dependent
random vectors may highly related to it.

Look forward to hearing from you.
Thanks a lot!

Xichu

**Comment by salu133445** [comment]
Hi Xichu,

The inputs are defined in this file.
https://github.com/salu133445/musegan/blob/master/input_data.py

For instance, if we're generating four-bar phrases. Then the time-independent random vector is shared and used to generate the four measures. However, each bar also has a time-dependent random vector, which is responsible for time-variant features.

We didn't apply other tricks to produce these factors. All the random vectors are sampled a normal or a uniform distribution.

**Comment by salu133445** [comment]
You may also find some of these slides helpful.

https://salu133445.github.io/musegan/pdf/musegan-aaai2018-slides.pdf

**Comment by maxichu** [comment]
Thank you so much!
