### ISSUE TITLE
have a question about the latest source code

### ISSUE THREAD

**Issue by INotWant** [salu133445/musegan#80]
Your paper is very good and I has benefited a lot.
But I have a bit question about the latest source code. I see that `conv3d` already contains the time structure, so we don't need to model the temporal structure by myself?
If that, Can it bring better results?
Thank you!

**Comment by salu133445** [comment]
The latest implementation is based on the network architectures presented in [BinaryMuseGAN](https://salu133445.github.io/bmusegan/pdf/bmusegan-ismir2018-paper.pdf), in which the temporal structure is handled as yet another axis using 3D convolutional layers. So, basically yes.

We did not actually know which architecture works better. The advantage of this design is its smaller network size, while the disadvantage lies in its lack of controllability (e.g., feeding different latent variables for different bars or tracks). It would be interesting to compare them in a systematic way.

**Comment by INotWant** [comment]
Ok, i get. Thank you very much!
