### ISSUE TITLE
如何生成一段指定时间长度的音乐，而不是多个小节拼在一起

### ISSUE THREAD

**Issue by yaningxu** [salu133445/musegan#82]
如何生成一段指定时间长度的音乐，而不是多个小节拼在一起

**Comment by salu133445** [comment]
Unfortunately, we only support fixed-length phrases in the current model. Each phrase is four measures long. If you would like to generate longer phrases, you might need a temporal model that can handle data with variable lengths.

目前的模型只能生成固定長度的音樂片段，長度則取決於訓練數據前處理後每個片段的長度。如果你希望生成更長的音樂片段，會需要更動模型的設計，如將temporal model換為RNN（目前是CNN）。
