### ISSUE TITLE
ValueError: Cannot get beat timings to quantize pianoroll.

### ISSUE THREAD

**Issue by fnyhy** [salu133445/musegan#83]
你好！我在使用pypianoroll进行音乐生成时会出现以下报错：
File "/data1/qxh/anaconda3/envs/deepj/lib/python3.5/site-packages/pypianoroll/multitrack.py", line 700, in parse_pretty_midi
    raise ValueError("Cannot get beat timings to quantize pianoroll.")
我自己写的 pattern=Multitrack(tracks=['piano1', 'piano2', 'piano3', 'piano4', 'piano5'], tempo=array([120., ... 120.]), downbeat=array([ True, False,...,False]), beat_resolution=24, name=unknown)。pattern.write('filename.mid')写入以后，再进行d=Multitrack('filename.mid'),就会出现上述报错。:-( 我自己写的这个pattern是有什么问题吗？

**Comment by salu133445** [comment]
Sorry for the late reply. Have you fixed the problem? If not, could you please run `pm.estimate_beat_start()` to see whether the first beat time is estimated correctly.

**Comment by fnyhy** [comment]
I have fixed it. Thanks!

**Comment by salu133445** [comment]
Cool!

**Comment by arash-sadeghi** [comment]
Hi, can you explain how did you resolve the issue? I am still struggling with it.
