### ISSUE TITLE
How to conditionate a track

### ISSUE THREAD

**Issue by gregschuit** [salu133445/musegan#85]
Hi, i would like to train the algorithm conditionating a particular track, but usign is_conditional parameter, the error "Not supported yet" raises. On the other hand, the parameter is_accompaniment also raises some errors. 

Is there a correct way to do this?

**Comment by salu133445** [comment]
The accompaniment model has not been implemented yet in the latest version. You might need to run the code of v2 (or v1) for the track conditional case.

**Comment by moonsh** [comment]
@salu133445   Where I can find the code of v2 for the track conditional case ?
