### ISSUE TITLE
Learning on sparse MIDI

### ISSUE THREAD

**Issue by aashiqmuhamed** [salu133445/musegan#87]
This is more of a question than an issue but did you find difficulty learning using Convnets when your dataset is mostly sparse? ie. when you don't merge several tracks together

My GAN seems to predict all zeros.

**Comment by salu133445** [comment]
Hi, from our experience, GANs with proper regularizations, e.g., gradient penalties and/or spectral normalization, are able to handle sparse data. Also, the outputs will become close to zero at the beginning of the training. You should wait for a while to see it improves.
