### ISSUE TITLE
track-conditional generation

### ISSUE THREAD

**Issue by gxd1994** [salu133445/musegan#9]
hello, I'm quite interested in your work. 
I'm confused about track condition generation. My understanding is that the bars that are produced now are determined by the previous bars. But, i didn't find the relevant code. I also confused about config.acc_idx, What does it mean?  Looking forward to your reply.   thx
![image](https://user-images.githubusercontent.com/15042705/38741705-19f2d852-3f6d-11e8-87d7-7bf3018e20b4.png)

**Comment by wayne391** [comment]
Hello, our previous work - MidiNet (https://github.com/RichardYang40148/MidiNet) is actually condition on previous bar to model the temporal dependencies. However, in our work, we achieve this by using another convnet generator (phrase generator).  The phrase generator generates N vectors simultaneously,  and then the bar generator takes these N vectors as inputs to generate N bars. 

So, the only thing that the "track condition generation" need to do is accompaniment - Encoding one specific current track and let network condition on it. In configuration, you can set the accompanied track by assigning "acc_idx" variable. For example, if we want to accompany piano track in our training data, we will set the "acc_idx" to "-1".

**Comment by gxd1994** [comment]
Thank you for your reply. if batch size is set to 64, use function of save_midis to save file , But why just get only one midi file? Why didn't get 64 files? Looking forward to your reply. thx

**Comment by wayne391** [comment]
We save all generated samples  into one midi file and put empty bars between two samples.
