### ISSUE TITLE
FileExistsError: Cannot process data due to SharedArray naming

### ISSUE THREAD

**Issue by nicholaschiang** [salu133445/musegan#92]
In `src/process_data.py`, it appears that you name the `SharedArray` the name of it's source `.npz` file:
```python
        with np.load(filepath) as loaded:
            print("Saving data to shared memory.")
            sa_array = sa.create(name, loaded['shape'], dtype)
            sa_array[[x for x in loaded['nonzero']]] = True
```
Where `name` is defined as:
```python
        name = os.path.splitext(os.path.basename(filepath))[0]
```
This seems to be causing a `FileExistsError` at runtime:
```bash
(.venv) nchiang@eevee ~/repos/musegan (master) $ ./scripts/process_data.sh
Loading data from '/home/nchiang/repos/musegan/scripts/../data/train_x_lpd_5_phr.npz'.
Saving data to shared memory.
Traceback (most recent call last):
  File "/home/nchiang/repos/musegan/scripts/../src/process_data.py", line 47, in <module>
    main()
  File "/home/nchiang/repos/musegan/scripts/../src/process_data.py", line 40, in main
    sa_array = sa.create(name, loaded['shape'], dtype)
FileExistsError: [Errno 17] File exists: 'train_x_lpd_5_phr'
```
Why are you naming the `SharedArray` exactly the same as the `.npz` file that is being loaded into it (the `SharedArray`)? Any suggestions?

**Comment by nicholaschiang** [comment]
[Current workaround](https://github.com/nicholaschiang/musegan/commit/04d6a92e3c79cd7ecd397a686f732a3cb7e203ab) is just to specify a `prefix` in `scripts/process_data.sh`:
```bash
#!/bin/bash
# This script store the training data to shared memory.
# Usage: process_data.sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
python "$DIR/../src/process_data.py" "$DIR/../data/train_x_lpd_5_phr.npz" --prefix "shm://"
```

**Comment by salu133445** [comment]
Hi, thanks for reporting. The default storage destination for SharedArray should be different from the current working directory, and thus the FileExistsError should not happen. Have you checked if you already have a file of the same name in the shared memory? Note that even if the script exits with errors, as long as `sa.create(xxx)` is executed, the shared array will then be created. Let me know if it is the case.

**Comment by nicholaschiang** [comment]
Gotcha. So my problem is just that I already have that filename in shared memory on my machine (and thus `src/process_data.py` should check for that and give a prompt asking to delete it).
