### ISSUE TITLE
install error...An error occurred while installing tensorflow-gpu==1.10.1

### ISSUE THREAD

**Issue by xiaoxiongke** [salu133445/musegan#94]
An error occurred while installing tensorflow-gpu==1.10.1 --hash=sha256:2872b24f8c86bd16c8667bed0346b68ba8472f6c4d47c5554c560faf5f5bc64a --hash=sha256:5b1b4a34c8631b2c30d11c6eb83c9c7c5700c06c51d761e842da1a8f839f51a3 --hash=sha256:bcb1703fe27a1248c7768c2143a33b025872b007bb9699e6282cc98474c3b8c3 --hash=sha256:d7e1dcc722541be88c8fad4219314313d97af129b3e3567c5c20daecfb7f8593 --hash=sha256:e83febd2c21c9cd05d00f11276458ae69af11d3656483018aa9897143669d65d! Will try again.
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.org/simple, https://pypi.apple.com/simple']
[pipenv.exceptions.InstallError]: ['ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.10.1 (from -r /var/folders/qp/0n1xpkbn2vb3sqlp22vb2xf80000gn/T/pipenv-2bpwcvmi-requirements/pipenv-3xxa9__y-requirement.txt (line 1)) (from versions: 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0rc2, 1.1.0)', 'ERROR: No matching distribution found for tensorflow-gpu==1.10.1 (from -r /var/folders/qp/0n1xpkbn2vb3sqlp22vb2xf80000gn/T/pipenv-2bpwcvmi-requirements/pipenv-3xxa9__y-requirement.txt (line 1))']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:01

What's wrong?

**Comment by salu133445** [comment]
It seems to result from the Python version. You are using Python 3.7, while we used Python 3.5. Please refer to this issue (https://github.com/tensorflow/tensorflow/issues/8251). Thanks.

**Comment by xiaoxiongke** [comment]
> It seems to result from the Python version. You are using Python 3.7, while we used Python 3.5. Please refer to this issue ([tensorflow/tensorflow#8251](https://github.com/tensorflow/tensorflow/issues/8251)). Thanks.

Thank you very much.

**Comment by salu133445** [comment]
I have removed the Python version requirement from Pipfile. Either Python 3.5 or 3.6 should work. Thanks.
