### ISSUE TITLE
Add libcublas nvidia driver dependency docs

### ISSUE THREAD

**Issue by nicholaschiang** [salu133445/musegan#96]
The Tensorflow version that is being used here (`tensorflow-gpu@1.10.1`) only supports NVIDIA's `libcublas.so.9.0` driver which is rather outdated and [only supports an older set of operating systems](https://developer.nvidia.com/cuda-90-download-archive).

I'm currently running Ubuntu 18.0.4 which [is supported](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal) by NVIDIA's `libcublas.so.10.0` drivers (but not the older driver that `tensorflow-gpu@1.10.1` requires).

While I would suggest that you [upgrade your Tensorflow version to support CUDA 10 drivers](https://www.tensorflow.org/install/gpu#linux_setup), it would be great if you could at least add some documentation of this problem and required hardware setup to your `README.md`.

**Comment by nicholaschiang** [comment]
@salu133445 Updating `tensorflow-gpu` to v1.13.1 should fix this.

**Comment by salu133445** [comment]
@nicholaschiang  TensorFlow, CUDA and Ubuntu versions are somehow tricky here. I believe there is no trivial way to handle the version issue. I would prefer to keep the original versions. For people using different CUDA and Ubuntu versions, they might want to install a different version of TensorFlow based on their CUDA and Ubuntu versions. 

![image](https://user-images.githubusercontent.com/22392791/72926791-de316300-3d09-11ea-9aa0-455835bd5de8.png)
