### ISSUE TITLE
preparing new dataset with structure features

### ISSUE THREAD

**Issue by VladJamir** [salu133445/musegan#97]
I'm currently creating a jazz dataset with structure features. I am looking at `musegan/v1/training`. In 
`tracks_parsing.py` you used `LMD` instead of `LPD`, from what I understand it is here that you convert the `LMD` to `LPD-5` given a `jazz_ids`. 
However, I already created an `lpd-5-jazz` dataset using [lakh-pianoroll-dataset](https://github.com/salu133445/lakh-pianoroll-dataset). The only difference is that it does not have the same directory structure with the result in `tracks_parsing.py` since it was not structure in the form of `[instrument_name]/[msd_id].npz`.
My question is that if should I use the `tracks_parsing.py` for conversion or is there a code for structuring the already structured dataset into this `[instrument_name]/[msd_id].npz`.

**Comment by VladJamir** [comment]
Follow up question: where do I get the `midi_dict.json`?

**Comment by VladJamir** [comment]
I got this error, I downloaded the LMD-matched dataset from [The Lakh MIDI Dataset by Colin Raffel](https://colinraffel.com/projects/lmd/)
```
File "tracks_parsing_jazz.py", line 119, in <module>
    with open(instrument_dict_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vladjamir/training/lmd_matched/lmd_matched/1/e/a/cb1ea79d6bd7bb21fbfc930b83a9bc13/instruments.json'
```
does this mean that i should have downloaded the LMD-matched with the metadata?

**Comment by salu133445** [comment]
Hi, please check out this [repository](https://github.com/wayne391/symbolic-musical-datasets/tree/master/5-track-pianoroll) for strategies on prepare training data from a collection of MIDI files.
