### ISSUE TITLE
change the size of training data

### ISSUE THREAD

**Issue by ErisGe** [salu133445/musegan#99]
I saw that your answer about training data'size, and said that 'by setting the length of the first axis to a smaller number'. But how can I change this value?

`def load_data_from_npz(filename):
    """Load and return the training data from a npz file (sparse format)."""
    with np.load(filename) as f:
        data = np.zeros(f['shape'], np.bool_)
        data[[x for x in f['nonzero']]] = True
    return data`

**Comment by salu133445** [comment]
Hi, you can replace the last line with `return data[:5000]` for example.

**Comment by ErisGe** [comment]
Oh, thank you so much!
